plugins {
    id 'java-library'
}

group = 'com.twilio'
version = '8.18.0'

description = "Twilio API"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api "com.twilio.sdk:twilio:8.18.0"
    api "com.google.guava:guava:33.4.0-jre"

    testImplementation "junit:junit:4.13.2"
    testImplementation "org.mockito:mockito-core:5.23.0"
}
